language: node_js
sudo: false
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
env:
  global:
  - secure: vXhVskyAfuqrC7e2xhtImNOQpLGxoJQ5JdrBV5Q9AzxOoJXjf7nqpGpuLgNC51z94+eAqbQ8opbZafYEDas0ZDH8BL5/prXj8vhTeAKCxA8vU7nq5i2FUY+4VgY4Q07loY1ybPqe3SFTlQ69/VOPvjjlBKYqMmSNnSkhjHi+PC8Akr+ZcqkOCVwmzekt27fvawO6pj8PKF0XqW/Bh8qHQXCrYDffVhW0cqgONRk2HsRcDEj3pDnfVCpBNTL51gzsa2EDBioRQLW5GTVNtwmfuCHJvo88qtQ63bVQ+w0wYvWWFuf8Gcss3o9TN0PuhYgXclvQaAYiLAhulbfRoDRE1RCdOylndtWecqALmWO+Mpxp578Qr1YLfbjckUf6CFDDaXKbGBgsMMHTivBE1YU+jo/Zcn72Q0ItTd7GFOew+VsoXULRDJTokchDt4771snZcktJzXrOJOfI91n11uTvNvbipjN37D3V51dTNjMuv+9/P4KFIWXymmQV+FRNjh6XfnzXZ3HI0myUJWSmkAMBfOKm8bmkJIb9ViWl+/eRuf6nsQKuV8KoplHQeQ8Y7AGJ/pozOHnPhhHPq6tULED5qxpIo/f2TwrMUnZkYr9x9yT/QJsaMm6wQ25JSsdXqksueArQ2ecXp7xiHIQ5exP80sG2q+gakzcf+dkmq5A40ZI=
  - secure: SPvbE9pLerWZa3e5HSDEZfw6w3+6Wr+XRLpomciGFkC22bNy0NryQiilXHx8zh/4FtKqdwOZQyJc9LmjEEqk8lAnI6xqFmGJKLK5rtMzhQK3Q+tXhVsc6X48gPw3Fs+Nd74iorUWK3YQZgL3e5E5XQ77In6UqJ5b9BFXXdHn+J/U8u69zCYWUSnY/WMyNZAusAJ4CqeBba+Mndtd/v06kRz4aX8gRqFkmnPf5RdmoyiWWqgP1RrO3seXskluxOKj/qKifnvlPaHVziZ4u4hU07AiLAYo4YkuieQzk7dDbjp1QLm5mqQ1/Qfarq9C7BVnZuG8FYcTkBtZ+GgfjR+/Ww4ZvgpMPeNke5VnrnkGCemh+niW6IdwYguFlkL0ERBWH05VQ8UgiUoplcDxjJS05DUn6R9UVA97HJx1p+aAjA8n3iezXSrAELGcSxinLVwzIVFwE8pEPt6f2Cr5Qu0+fsRVr3ISf3nHlDow3JQCc5cGou3js0AcP9xPQpzfnQVdgvsmKOs69PD+OtdwVprW5QIZAWiI/syC6Yw4vfLpjk6nTYyN4IPUZuwv7nZ6Re7B7xWL7CAokzdalbQEQhP6Mi4ewt/FP/9HAuDQYsA/1t6LW8anFl2/AeTXCzPi6MDsIGUdNlTyG+h6vDcKjFZNmJTRbLsXvIH4e47dMKfR8lg=
  - CXX=g++-4.8
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    - ubuntu-toolchain-r-test
    packages:
    - google-chrome-stable
    - g++-4.8
  sauce_connect: false
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
